### ISSUE TITLE
No propper error handling if TLSv1.2 is not supported by PHP

### ISSUE THREAD

**Issue by meckhardt** [p7s1-ctf/7pass-php-sdk#18]
7Pass requires TLS 1.2, otherwise communication is not accepted.

PHP does not support TLS 1.2 prior to cURL version 7.34.0 (https://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html).

The SDK gives no warning, that the PHP environment does not support TLS1.2. Furthermore there is no way to configure the Guzzle client to switch SSL versions once it is available. PHP's default is `CURL_SSLVERSION_DEFAULT` which means that a proper SSL version should be determined by curl itself. This does not work currently, since curl (and PHP) quits with `SSL connect error`.

This can be reproduced by using curl on command line itself:

```sh
# Does not work
curl -sv https://sso.qa.7pass.ctf.prosiebensat1.com/.well-known/openid-configuration
# Works
curl -sv https://sso.qa.7pass.ctf.prosiebensat1.com/.well-known/openid-configuration --tlsv1.2
``` 
Environment:

```sh
$ cat /proc/version
Linux version 2.6.32-573.18.1.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Feb 9 22:46:17 UTC 2016

$ yum list installed | grep curl
curl.x86_64                      7.19.7-46.el6          @mirror-centos-base     
libcurl.x86_64                   7.19.7-46.el6          @mirror-centos-base 
```

**Comment by matuszeman** [comment]
Hi @meckhardt, thanks for reporting this. This should definitely be covered in README.md also.
What would you expect proper handling to be?

**Comment by matuszeman** [comment]
Let me check how we can force TLS1.2 to be used by default by Guzzle client.

**Comment by matuszeman** [comment]
To check with you @meckhardt.
I'm proposing the following:

1. Add SDK dependencies:
  - lib-curl 7.34.0
  - ext-curl *
2. Force guzzle client to use TLS1.2 only.

What do you think?

**Comment by meckhardt** [comment]
@matuszeman just an ideo for proper error handling: Check if TLSv1.2 is supported by used PHP environment. If not throw meaningful exception.

Enforcing TLSv1.2 should be fine for me.

**Comment by meckhardt** [comment]
@matuszeman btw RHEL seem to provide TLSv1.2 below libcurl 7.34.0. So probably we should not use requirements in composer.json.

**Comment by matuszeman** [comment]
OK it seems like only feasible way how to handle this is:
- document it - https://github.com/p7s1-ctf/7pass-php-sdk/pull/21/files#diff-04c6e90faac2675aa89e2176d2eec7d8R16
- set TLS 1.2 curl option on the client: https://github.com/p7s1-ctf/7pass-php-sdk/pull/21/files#diff-10293097bd01f3e808ac65f998e235d9R49

Would you mind to test it in your environment please?
https://github.com/p7s1-ctf/7pass-php-sdk/tree/mz/18_tls12

**Comment by matuszeman** [comment]
@meckhardt did you manage to try it out?
